version: '2'
services:
  todolist:
    container_name: emumba
    image: docker.io/tayyab80/emumba:v1
    # restart: always
    env_file: .env
    command: gunicorn emumba:v1 -w 2 -b :8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  migration:
    container_name: migration
    build: .
    image: docker.io/tayyab80/emumba:v1
    env_file: .env
    command: flask db upgrade
    depends_on:
      - todolist
